# pull the base image
FROM node:lts-alpine

# set the working direction
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./

COPY yarn.lock ./

# Install all packages
RUN yarn

# add app
COPY . ./

# Install serve which is used to host the prodcution build
RUN npm i serve -g

# Build in production mode
RUN npm run build

# # start app
# CMD ["yarn", "start"]

# # Serve the production build
CMD serve -s build