exports.MISSING_REQ_BODY = "Missing request body";
exports.MISSING_SOME_INPUT = "Missing some input";
exports.INVALID_ID = "Invalid question id, cannot parse";
exports.QUESTION_DOES_NOT_EXIST = "Invalid question id, question does not exist";
exports.INVALID_DIFFICULTY = "Invalid difficulty, not of 'easy', 'medium' or 'hard'";
exports.INVALID_HTTP_METHOD = "Invalid HTTP Method";
exports.INVALID_API_ENDPOINT = "Invalid api endpoint";
exports.JWT_AUTH_FAILED = "You are not authenticated!";
exports.AUTHORIZATION_FAILED = "You are not authorized!";
